bochs-emu/Bochs

bochs/.bochsrc
bochs/doc/docbook/user/user.dbk

This change adds 4 missing pre-defined CPU model names. This is document-only change. 
Review commit by commit. The first commit is trailing space removal only. 2nd commit is the actual change. Model descriptions are as appear in the `brand_string`, followed by generation names.

Update predefined CPU lists in the documents  

---

bochs/bx_debug/dbg_main.cc
bochs/bx_debug/debug.h
bochs/bx_debug/lexer.l
bochs/bx_debug/parser.y

Layout support (our GDB-TUI for poors :D):
```
addlyt file - cause debugger to execute a script file every time execution stops.
Example of use: 1. Create a script file (script.txt) with the following content:
regs            
print-stack 7
u /10
<EMPTY NEW LINE>
2. Execute: addlyt "script.txt"
Then, when you execute a step/DebugBreak... you will see: registers, stack and disasm.
```
```
remlyt - stops debugger to execute the script file added previously with addlyt command.
```
```
lyt - cause debugger to execute script file added previously with addlyt command.
Use it as a refresh/context.
```
Example of use:
Re-execute layout:
IMO, this will be **one of the most used features**.  (search_in_history or write same commands each time its a pain in the ass)
One idea: the user can have some …

add layout commands for dbg

---

bochs/bx_debug/dbg_main.cc
bochs/bx_debug/lexer.l
bochs/bx_debug/parser.y
bochs/doc/docbook/user/user.dbk

Add help for **three** existing commands: **bt**, **source** & **print-string**
NOTE: **source** command is implemented in **dbg_main.cc** (for this reason I only add **BX_TOKEN_SOURCE** for **help source** command)

add dbghelp for source, bt and print-string commands

---

bochs/doc/docbook/user/user.dbk

Fix dbgdoc user.dbk broken with PR #12 
Reported by @vruppert: 
https://github.com/bochs-emu/Bochs/commit/d514779177e88235ed00c11546ee732ad86e233e#commitcomment-84314677
Sorry for my fault, it was my first time with this kind of doc :\
Web output with this PR:

Fix dbgdoc user.dbk broken with PR #12

---

bochs/build/win32/nsis/bochs.nsi.in

Added silent uninstall command for use by WinGet and other packaging tools.
I also made the strings non-expandable because $InstDir will never contain %ProgramFiles% etc.

Register Windows silent uninstall command

---

bochs/build/win32/vs2019-workspace/vs2019/avx.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/cpu.vcxproj

Few new files are required to build Bochs on Windows but not included in the Visual Studio solution. Add them and fixes link errors.

Fix windows build

---

bochs/cpu/cpu.cc

It seems that sometimes breakpoints do not fire if there are several cpu.
To reproduce this issue, try to launch Bochs with the following configuration file:
```
memory: guest=64, host=64
romimage: file=$BXSHARE/BIOS-bochs-latest
vgaromimage: file=$BXSHARE/VGABIOS-lgpl-latest
cpu: model=core2_penryn_t9600, count=2
```
Then run bochs, enter the following commands:
```
bp 0xfe063
c
```
Observe that the breakpoint does not work, the execution continues until simulation is killed due to absence of bootable device.
If the breakpoint does work, try to break on nearby instructions instead, it is not easy to reproduce the issue 100% accurately.
It seems that when there are several reasons to stop cpu_loop, as soon as the first reason is found, checks for other reasons are skipped. So, when …

Check breakpoints before icount guard

---

bochs/aclocal.m4
bochs/configure
bochs/configure.ac

C99 removed implicit function declarations from the language.  All functions must be declared before they can be called.  There are a few places in the configure script where the exit function is called without including <stdlib.h>.  Instead, return from the main function, avoiding the exit declaration issue.

configure: Improve compatibility with strict(er) C99 compilers

---

bochs/gui/win32.cc

With newer wider screens, we can now have wider statusbar elements so that an element such as "USB-HD" isn't clipped on both sides.

Wider statusbar elements

---

bochs/iodev/hpet.cc
bochs/iodev/hpet.h

Patched an issue with the HPET where writing an u64 with HPET_TN_SETVAL set, would only write the lower 32bits into the comparator. This is because the write is getting split into two 32bit writes and the first 32bit write will disable HPET_TN_SETVAL.

patched an issue with the HPET

---

bochs/cpu/cpudb/amd/turion64_tyler.cc
bochs/cpu/cpudb/intel/corei7_icelake-u.cc
bochs/cpu/cpudb/intel/tigerlake.cc

This was caught by ASAN. The brand_string is copied as:
```
void bx_cpuid_t::get_ext_cpuid_brand_string_leaf(const char *brand_string, Bit32u function, cpuid_function_t *leaf) const
{
switch(function) {
case 0x80000002:
memcpy(&(leaf->eax), brand_string     , 4);
memcpy(&(leaf->ebx), brand_string +  4, 4);
memcpy(&(leaf->ecx), brand_string +  8, 4);
memcpy(&(leaf->edx), brand_string + 12, 4);
break;
case 0x80000003:
memcpy(&(leaf->eax), brand_string + 16, 4);
memcpy(&(leaf->ebx), brand_string + 20, 4);
memcpy(&(leaf->ecx), brand_string + 24, 4);
memcpy(&(leaf->edx), brand_string + 28, 4);
break;
case 0x80000004:
memcpy(&(leaf->eax), brand_string + 32, 4);
memcpy(&(leaf->ebx), brand_string + 36, 4);
memcpy(&(leaf->ecx), brand_string + 40, 4);
memcpy(&(leaf->edx), brand_string + 44, 4); …
```

cpudb: extend strings that are too small

---

bochs/.bochsrc
bochs/config.cc
bochs/doc/docbook/user/user.dbk
bochs/iodev/usb/Makefile.in
bochs/iodev/usb/scsi_device.cc
bochs/iodev/usb/usb_common.cc
bochs/iodev/usb/usb_common.h
bochs/iodev/usb/usb_ehci.cc
bochs/iodev/usb/usb_floppy.cc
bochs/iodev/usb/usb_hid.cc
bochs/iodev/usb/usb_hub.cc
bochs/iodev/usb/usb_msd.cc
bochs/iodev/usb/usb_msd.h
bochs/iodev/usb/usb_printer.cc
bochs/iodev/usb/usb_uasp.cc
bochs/iodev/usb/usb_xhci.cc
bochs/iodev/usb/usb_xhci.h
bochs/param_names.h

Added examples for new options.
- xhci: model= option
- xhci: allow the user to select number of ports
- usb disk: proto= option (bbb or uasp)
Added xhci primary stream support.
(Secondary stream support is not included)
Added (experimental) usb disk protocol UASP for super- and high-speed usb disk devices.
(high-speed uasp support is not thoroughly tested)
xhci: fixed "change event" function
scsi: fixed bug in command 0x25
scsi: added command 9E/10

 USB emulation update

---

bochs/iodev/usb/usb_common.cc
bochs/iodev/usb/usb_pcap.cc
bochs/iodev/usb/usb_pcap.h

The 'd.pcap_image_t pcapture' in usb_common.h called its constructor and set 'fd' to -1. However, in the usb_device_c() constructor, we then cleared all of 'd', resetting pcapture.fd back to zero. Then on Bochs exit, the pcap_image_t destructor tried to close the file since 'fd' was zero instead of -1. To fix this, I removed the pcap_image_t constructor and now call pcap_image_init() within the usb_device_c constructor.

Fix issue #25

---

bochs/config.cc
bochs/doc/docbook/user/user.dbk
bochs/iodev/usb/uhci_core.cc
bochs/iodev/usb/uhci_core.h
bochs/iodev/usb/usb_ehci.cc
bochs/iodev/usb/usb_ehci.h
bochs/iodev/usb/usb_hub.cc
bochs/iodev/usb/usb_hub.h
bochs/iodev/usb/usb_ohci.cc
bochs/iodev/usb/usb_ohci.h
bochs/iodev/usb/usb_uasp.cc
bochs/iodev/usb/usb_uhci.cc
bochs/iodev/usb/usb_uhci.h
bochs/iodev/usb/usb_xhci.cc
bochs/iodev/usb/usb_xhci.h

This adds over-current signaling to the USBs four host controllers.
To signal an OC, use the runtime configuration and set the checkbox (GUI) or text config's parameter to 1.
This pull request also adds USB documentation to user.dbk.

Add over-current signaling

---

bochs/doc/docbook/user/user.dbk
bochs/iodev/usb/scsi_device.cc
bochs/iodev/usb/scsi_device.h
bochs/iodev/usb/uhci_core.cc
bochs/iodev/usb/uhci_core.h
bochs/iodev/usb/usb_common.cc
bochs/iodev/usb/usb_common.h
bochs/iodev/usb/usb_ehci.cc
bochs/iodev/usb/usb_ehci.h
bochs/iodev/usb/usb_floppy.cc
bochs/iodev/usb/usb_floppy.h
bochs/iodev/usb/usb_hub.cc
bochs/iodev/usb/usb_hub.h
bochs/iodev/usb/usb_msd.cc
bochs/iodev/usb/usb_msd.h
bochs/iodev/usb/usb_ohci.cc
bochs/iodev/usb/usb_ohci.h
bochs/iodev/usb/usb_uasp.cc
bochs/iodev/usb/usb_uhci.cc
bochs/iodev/usb/usb_xhci.cc
bochs/iodev/usb/usb_xhci.h
bochs/plugin.h

- fixed default speed setting
- Now checks for a valid speed of a device depending on the Host Controller as well as the device's allowed speeds.
- fixed SCSI:Request Sense
- fixed SCSI:Mode Sense
- fixed SCSI:Inquiry
- added SCSI:Get Configuration
- added SCSI:Request Sense: ASC and ASCQ
- USBMSD now handles short packets instead of returning s.datalen (s.scsi_len is now returned)
- added the start of UASP Task Management
- UASP: Return Status includes Sense
- fixed xHCI:SET_TR_DEQUEUE command
- fixed resetting of the TD's toggle bit
- I have had all devices work on Win95, Win98, WinXP, Win7, Win8, and Win10, except for a few quirks with 
Super-speed CD-ROMs, EHCI's UASP support, and num_lock states with HIDs.
- Added more documentation to user.dbk
To be fixed:
- USBMSD write in WinXP …

Updates to USBMSD/SCSI emulation

---

bochs/bx_debug/dbg_main.cc

Before this PR **info idt** on **protected 32** (windows xp sp3 x86)
As you can see the symbol exists but is not showed with **info idt**
So, with this PR:

add symbol info to info idt on protected 32

---

bochs/bochs.h
bochs/cpu/cpu.cc
bochs/gdbstub.cc

While using breakpoints exceed 4GB limit, I noticed that they not work. This PR fixes it.

Fix for gdbstub with x86-64 that truncates instruction pointer while breakpoint check

---

bochs/.bochsrc
bochs/PARAM_TREE.txt
bochs/config.cc
bochs/cpu/io.cc
bochs/doc/docbook/user/user.dbk
bochs/param_names.h

By enabling the 'all_rings' option, you can utilize the port e9 hack from ring3
IMO very useful for:
- user-mode sandbox (ex Cuckoo)
- malware analysis
- API/SYSCALL logger with a simple hook from ring3
- automation + instrumentation from user mode code
- ...
So yes, from this PR a user-mode-sandbox can display on the console of the system running Bochs anything that is written to 0xE9 port
**This PR is 100% backward compatibility**
btw, @stlintel I'm not certain if **bochs/config.cc** is the ideal location to define **bool port_e9_hack_all_rings** (unmapped io/dev is better?)

add port e9 hack support for all rings

---

bochs/.bochsrc
bochs/PARAM_TREE.txt
bochs/config.cc
bochs/cpu/io.cc
bochs/doc/docbook/user/user.dbk
bochs/param_names.h

This PR is for "I/O Interface to Bochs Debugger" from ring3 (port range: **0x8A00 - 0x8A01**)
PR #64 was for E9 HACK (port **0xE9**)
By enabling the iodebug's 'all_rings' option, you can utilize the port I/O Interface to Bochs Debugger from ring3. This PR allows the code running inside Bochs (ring3) to monitor memory ranges, trace individual instructions, and observe register values during execution.
https://bochs.sourceforge.io/doc/docbook/development/debugger-advanced.html
IMO very useful for:
- user-mode sandbox (ex Cuckoo)
- malware analysis
- API/SYSCALL hook/monitor from ring3
- automation + instrumentation from user mode code
...
A complement for PR #64
**This PR is 100% backward compatibility**
btw, @stlintel I'm not certain about:
- if misc is the ideal location for this.. should …

add iodebug support for all rings complement #64

---

bochs/iodev/usb/uhci_core.cc

The check for the amount of byte transferred in one frame time was done before the update of the vertical pointer in the current Queue of the last executed TD.  Therefore, on the next frame time, the last executed TD was being "executed" again. The check has now been moved to the top of the loop.

fixed bandwidth overage detection

---

bochs/iodev/usb/usb_common.cc
bochs/iodev/usb/usb_common.h

This fixes zero length packet handling.
See the following example that requests 128 bytes:
```
SETUP(8)
IN(64)
IN(64)
STATUS(0)
```
The current code erroneously assumes that there are no more IN packets after the first two 64-byte packets.
However, what happens with the following:
```
SETUP(8)
IN(64)
IN(64)
IN(64)    <--- current code assumes this will be, and expects a STATUS packet
STATUS(0)
```
Currently, the third IN(64) above will result in a coding error because the code is expecting the STATUS packet, not another IN packet.
The "controller" must allow for more packets than expected, returning a short packet detect on the third IN(64) packet shown above, actually returning zero bytes, hence the Short Packet Detect.
This patch was tested on WinXP, Win7, and Win10.

Fix zero length packet handling

---

bochs/iodev/usb/usb_xhci.cc
bochs/iodev/usb/usb_xhci.h

This adds three additional checks to make sure the Guest is working correctly.
- checks that the guest allocated the Scratchpad Area. If left zero (NULL) the controller may access low memory.
- checks that the guest uses correct segment sizes in the interrupter ring(s)
- checks the burst size value given to be within normal range
This also adds an internal register value for the HcCrcr (Command Ring Control) register. Since this register reads zero by the Guest, we keep an internal value so that the emulation can read the value, internally.  This is for features soon to be released.
Minor other syntax/comment changes (misspelled word, etc)
Checked with WinXP, Win7, and Win10

Additional controller checks

---

bochs/iodev/usb/uhci_core.cc
bochs/iodev/usb/usb_common.cc
bochs/iodev/usb/usb_common.h
bochs/iodev/usb/usb_ehci.cc
bochs/iodev/usb/usb_ohci.cc
bochs/iodev/usb/usb_xhci.cc

This improves the detection of the default speed of a device when given in bochsrc.
It will first get the max speed of the port given. For example, uhci and ohci will return FULL, ehci will return HIGH.
xHCI will return SUPER if the port is a super-speed port, else it will return HIGH.
Then it will compare this with the max speed allowed for that device, returning the highest common speed.
Of course, if the speed option is given, the above is overwritten by the specified speed.
Both checks are still performed on the result.
1) does device allow the result speed?
2) does the controller allow the result speed?

Improve default device detection

---

bochs/iodev/hdimage/vpc.cc
bochs/iodev/hdimage/vpc.h

This PR allows larger VHD image files.  The size in question doesn't necessarily mean the size of the VHD file on disk. The size is the total size of the image emulated. This total size is in question.
Without this patch, the total size allowed is 65535 * 16 * 255, or roughly 32gig.
With this patch, the total size is calculated by who the creator of the image is, what the CHS values are, and possibly a total size of up to a limit of 2TB.
Since the original code was ported from QEMU, I ported an updated QEMU code snippet. 
https://gitlab.com/qemu-project/qemu/-/blob/master/block/vpc.c?ref_type=heads#L305
This PR now allows VHD image files with a total size emulated less than or equal to 2TB.

Allow large VHD files

---

bochs/iodev/usb/scsi_device.cc

This changes a BX_INFO to a BX_DEBUG. It does not needed to be a BX_INFO.
Second, this adds (very) minimal support for SCSI command 0xAC.
When emulating a .iso image via USB CD-ROM on Win10, without this command, the emulation freezes when trying to access the CD-ROM. I don't know if it is Bochs or Win10. I think Win10 expects the command to work, or Bochs is not failing correctly.
This PR simply adds code to acknowledge the command and returns a zero length report. This SCSI (MMC) specification states that a zero length report is allowed.
The 8 byte header is returned, but the header indicates a zero byte return: No report segments returned.
This seems to keep Win10 from freezing at USB CD-ROM device access time.
The code also BX_DEBUG's the command sent to the "controller", for future …

Add minimal support for MMC command 0xAC

---

bochs/iodev/usb/usb_ohci.cc
bochs/iodev/usb/usb_ohci.h

This fixes the toggle bit check in the OHCI.
Tested Guests: WinXP, Win7
Tested devices: HID, HUB, DISK, CD-ROM

Fix OHCI Toggle function

---

bochs/iodev/harddrv.cc
bochs/iodev/harddrv.h

This fixes the CD-ROM hardware by making sure the `drive_ready` flag is zero after an `ATAPI_DEVICE_RESET` command. As far as I know, no other Guest needed this fix except for the TEAC-CDI driver referred to below.
This also adds an assumption fix so that the TEAC_CDI driver will work.
The TEAC_CDI driver relies on the fact that the TEAC drive it is designed for, sets the `interrupt reason` register (`sector count` register) after the `ATAPI_IDENTIFY` command is issued. It uses this `i_o` bit of this register to determine the direction of transfer for the 0xA1 command, even though this is a read-only direction command.
Through other tests, I see no other Guests effected by this addition.
I also added a few minor syntax modifications, tab spacing, and comments. The DEBUG out string will …

A small fix and addition for a TEAC CD-ROM driver

---

bochs/config.cc

This fix adds the `companion=uhci\ohci` parameter to the saved config file on suspend.

write companion to save file

---

bochs/config.cc

This changes the recent PR to use get_selected() instead of hard coding the "uhci" and "ohci".
This also adds the xHCI options.

add ehci and xchi parameters to suspend config

---

bochs/iodev/usb/usb_floppy.cc
bochs/iodev/usb/usb_floppy.h

This adds support for the UFI_SEND_DIAGNOSTIC command in USB_FLOPPY.CC
and
This changes the list of defines to enum to match the current changes made to recent files.

Add DIAG command and change to enum

---

bochs/cpu/avx/avx512.cc
bochs/cpu/avx/avx512_cvt.cc

next step new methods for VEXPANDPS_MASK_VpsWpsR and VEXPANDPD_MASK_VpdWpdR with mask and memory operand will be introduced with fault suppression support
legacy load methods aren't good because the loads here actually read POPCNT(mask) elements from memory src

code refactor towards fixing issue #2

---

bochs/gui/gui.cc
bochs/gui/siminterface.cc
bochs/gui/siminterface.h
bochs/gui/win32config.cc

As an example, when saving the state of an emulation, especially one that has large image files and a large memory setting, there is a pause between the time you choose a directory to save to, and the MessageBox that states that the state was saved. During this time, there is no indication that Bochs is doing anything. As far as the user is concerned, Bochs froze.
So, this PR adds the capability to display a _Modeless_ message box. To do so, at any point you need a message box shown, allowing other things to continue to happen (SYNCHRONOUS), simply call the following line:
`void *hwnd = SIM->ml_message_box("Message Box Title", "Message Box Text");`
Then after the task has been performed, remove the message box:
`SIM->ml_message_box_kill(hwnd);`
The function is implemented in all …

Add Modeless MessageBox capabilities

---

bochs/iodev/usb/usb_ehci.cc

Simply change two BX_INFOs to BX_DEBUGs to keep from over populating the log file.

usb_ehci log fix

---

bochs/iodev/harddrv.cc
bochs/iodev/harddrv.h

This allows you to change the CD-ROM via the Bochs Ribbon, as well as properly "ejecting" a CD from the guest.
Before the CD path would change, but the guest (tested with WinXP and DOS as guests) would not see the change.
This fix simulates an open tray and then a closed tray for all CD changes.

fix ISO status change events

---

bochs/gui/gui.cc
bochs/gui/gui.h

When the user presses the "Reset" button on the gui ribbon, we need to clear the active status of all statusbar items or they remain set after the reset occurs.
This is mentioned in issue #123

reset status bar items at reset

---

bochs/CHANGES
bochs/iodev/hdimage/cdrom_win32.cc

The WIN32 configuration for the cdrom was not closing the image file on eject. This left the handle open while Bochs was running, not allowing the image file to be modified.

Close cdrom image file on eject

---

bochs/.bochsrc

The Legacy BIOS is incapable of handling a PCI enabled VGA rom, so added a warning to not use this particular combination.

Added warning note

---

bochs/build/win32/vs2019-workspace/vs2019/avx.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/bochs.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/bx_debug.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/cpu.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/cpudb.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/fpu.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/gui.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/iodev.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/iodev_display.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/iodev_hdimage.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/iodev_network.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/iodev_sound.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/iodev_usb.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/memory.vcxproj
bochs/build/win32/vs2019-workspace/vs2019/stubs.vcxproj

Enabling `assert`s in Debug MSVC builds (removing of `NDEBUG` defines) allows to catch more bugs.
No changes were made to `BX_ASSERT` handling.
Also I did not touched `vs2019-plugins` because it looks broken for me.

Enable asserts for MSVC Debug builds

---

bochs/memory/memory-bochs.h
bochs/memory/misc_mem.cc

These changes only have an effect when using a BIOS image designed for real hardware (tested with asus_p6np5.bin). When using Bochs BIOS no data will be saved / restored, since the 'flash_modified' value is always set to 'false'. Saving ESCD data on exit is not implemented yet, but it shouldn't be hard to do.

Added save/restore support for the ESCD space in the flash BIOS ROM.

---

bochs/iodev/display/banshee.cc

Fix memory corruption when reading Voodoo ROM

---

bochs/iodev/display/banshee.cc
bochs/iodev/display/voodoo.cc

Expand maximum resolution for Banshee and Voodoo 3 from 1600x1280 to 1920x1440

---

bochs/gui/win32.cc

`HWND_TOPMOST` should be cancelled with `HWND_NOTOPMOST` when it is not needed anymore.

Cancel topmost mode after leaving fullscreen mode

---

bochs/iodev/display/svga_cirrus.cc

Bits 5-6 of the left side clipping register have been implemented.

Cirrus: BLT System-to-screen Dword Pointer (GR2F[6:5]) implemented

---

bochs/iodev/usb/usb_xhci.cc
bochs/iodev/usb/usb_xhci.h

Was sending the SET_ADDRESS request using the wrong (old) slot context.

Fix XHCI Address Device command

---

bochs/cpu/apic.cc

According to Intel SDM vol3 11.12.10.2 (Deriving Logical x2APIC ID from the Local x2APIC ID), "The LDR initialization occurs whenever the x2APIC mode is enabled".

Init LDR whenever x2APIC mode is enabled

---

bochs/misc/bximage.cc

otherwise the question may not even arrive there, depending on the implementation-defined behaviour of stdio buffering.
fixes display of questions with musl libc.

bximage: flush stdout after asking a question

---

bochs/iodev/display/svga_cirrus.cc

It allows to use 1152x864x8 mode with [original BIOS](https://github.com/bochs-emu/Bochs/files/14130753/cl-gd5446_pci_vga_bios_version_1.31.zip).

Cirrus: Add support for palette modes with pixel frequency > 85 MHz

---

bochs/instrument/stubs/instrument.cc

The instrument stub needs this, otherwise
./configure --enable-instrumentation && make
fails because bxInstrument_c isn't declared.

Stub the bxInstrument_c class too

---

bochs/iodev/keyboard.cc

If not in wheel-mouse mode, don't report the wheel button event

wheel mouse button

---

bochs/memory/memory-bochs.h

OVMF is 4 megabytes by default, so in order to avoid customizing their build process we'll want to accommodate a 4M BIOS in Bochs.

Bump `BIOSROMSZ` to 4M to accommodate OVMF

---

bochs/config.cc

This allows the Window's Environment variable BX_SHARE_PATH to be used in paths within your bochsrc file.
Environment variable:
`BX_SHARE_PATH`
Value:
`D:\some\path`
Before:
`romimage: file=D:/some/path/bios/BIOS-bochs-latest`
After:
`romimage: file=$BXSHARE/bios/BIOS-bochs-latest`
Please note that I don't know why the parameter was initially empty. Was this to catch a base/default parameter? 
If the `lpValueName` parameter is NULL or an empty string, Windows will return a (possibly non-existent) default value.
With this PR, we specify the actual parameter of `BX_SHARE_PATH`.

Allow BX_SHARE_PATH to be used in BIOS paths

---

bochs/iodev/usb/ohci_core.cc
bochs/iodev/usb/ohci_core.h

The PSM bit is only valid if NPS = 0 and a few other minor additions and syntax fixes

check the nps bit before operating on the psm bit

---

bochs/cpu/cpuid.cc

Memory Protection Extensions - add MPX abbreviation
SMX: Secure Virtual Machine Technology - bit6 is for SMX, but [it's meaning](https://en.wikipedia.org/wiki/CPUID) is Safer Mode Extensions (part of TXT). Not Secure Virtual Machine Technology (which is already listed elsewhere as SVM).

Update cpuid.cc - label and abbreviation corrections SMX, MPX

---

bochs/cpu/apic.cc

Fixed spelling of word "destination" in log message.

Fixed spelling of word "destination" in log message

---

bochs/iodev/display/banshee.cc

Byte reversing code in commit 52c2fbee5e76f45c1725971634ebab2c984a9556 uses `8` bit shift, while `3` bit shift should be used instead.
Tested with Debian 7 _([hdd image](https://people.debian.org/~aurel32/qemu/powerpc/))_ inside of QEMU PowerPC emulation:

Fix big-endian support in bx_banshee_c::mem_read

---

bochs/iodev/usb/uhci_core.cc
bochs/iodev/usb/uhci_core.h

NAKs from USB devices do not deactivate TDs according to the official UHCI spec (page 22).
Reference: http://ftp.netbsd.org/pub/NetBSD/misc/blymn/uhci11d.pdf

UHCI: do not deactivate TDs on NAKs

---

bochs/Makefile.in
bochs/doc/docbook/Makefile.in

autoconf-based packages conventionally respect the DESTDIR environment variable rather needing to explicitly override it.
Likewise the distclean target is conventionally named distclean rather than dist-clean. This change adds a top-level alias to be compatible.
These changes are needed to build bochs on my infrastructure without having to special case bochs or locally patch it.

Get DESTDIR from the environment and add distclean target.

---

bochs/iodev/hdimage/vbox.cc
bochs/iodev/hpet.cc

These issues appear when -Werror=format on 32-bit platforms depending on the exact definitions of uint64_t and size_t.
It doesn't appear that bochs uses %zu for size_t -- since you support Windows platforms, unclear if that would work for you. If so, that's definitely correct rather than the unsigned long cast.

Fix printf format issues.

---

bochs/gui/enh_dbg.cc
bochs/gui/win32_enh_dbg_osdep.cc

The 'bytes' column is automatically resized to the width of the word 'bytes' (its header). This makes most instruction rows show `...`.
This patch defaults the width to 125 pixels allowing you to resize it during each session. However, every new session will default back to 125. A new entry in the `bx_enh_dbg.ini` file could be created to save and restore this size instead of defaulting to 125 each time.
This patch is for Windows only. Other platforms may require other modifications.

widen 'bytes' column

---

bochs/iodev/usb/uhci_core.cc

This PR fixes the frame number wrapping behaviour.
Previously it would incorrectly wrap around 1023 (0x3FF) instead of 2047 (0x7FF), causing behaviour to not match the specification. This PR makes it wrap around correctly.

UHCI: Fix erroneous frame number wrapping behaviour

---

bochs/bios/rombios.c

Issue: The high words of EAX, EBX and EDX are clobbered by int13_harddisk.
This can be checked by e.g. `TEST/DOSTEST.EXE` included with HX DOS Extender v2.21.
Affected games:
- Blackthorne (MS-DOS 6.22) shows corrupted player animations.
- others...
See also commit 140e2e9, 49736dd and 4d5d311.

BIOS: Fix register clobbering by int13_harddisk (#268)

---

bochs/iodev/display/voodoo_func.h

Allows to run 3DMark 99 Max benchmarks with Single Frame Buffer option set. Uses the same idea as bfebb17 (#349).

Voodoo3: Fix single buffered rendering of triangles

---

bochs/gui/win32usb.cc
bochs/iodev/usb/uhci_core.cc

- Fix Mask from 0x3FF to 0x7FF. The `actual count` is 11 bits.
- The i440bx has a PCI register at 0xFF in the configuration space. I give an error in the log file if it is written to.

Usb i440bx

---

bochs/config.cc
bochs/gui/gtk_usb_debug.cc
bochs/gui/gui.cc
bochs/gui/siminterface.cc
bochs/gui/siminterface.h
bochs/gui/usb_debug.cc
bochs/gui/usb_debug.h
bochs/gui/win32usb.cc
bochs/gui/win32usb.h
bochs/gui/win32usbres.h
bochs/iodev/usb/ohci_core.cc
bochs/iodev/usb/uhci_core.cc
bochs/iodev/usb/usb_ehci.cc
bochs/iodev/usb/usb_uhci.cc
bochs/iodev/usb/usb_xhci.cc
bochs/param_names.h
bochs/win32res.rc
bochs/win32usbres.rc

The function for some of the xHCI rings was never added to the USB_DEBUGGER code.
This should now allow you to see the DATA rings as well.
Use the `data=1` parameter:
```
usb_debug: type=xhci, doorbell=1, event=1, data=1
```

Xhci dbg fix

---

bochs/iodev/hpet.cc

The HPET allows reads and writes of 32-bit and 64-bit on 32-bit and 64-bit boundaries only.
This patch returns 0x00 and 0x0000 respectively for these reads and ignores these writes, giving an error in the log file.
This patch still PANICs on other reads and writes.

Return 0x00 on reads less than a dword

---

bochs/iodev/harddrv.cc
bochs/iodev/harddrv.h

- Fix the reading of the HOB registers
- return success on 0x37/0xF9 commands (still needs a little bit of work.)
- add the 0x46 (GET_CONFIG) command. This allows ReactOS 4.15.xxxx to boot in normal mode (LiveCD) LiveCD (Debug) still hangs. Most likely a different issue.
- the SENSE was not being cleared between commands. If one command failed, the next successful command would still show the failed SENSE values.

fix and enhance harddrv

---

bochs/iodev/harddrv.cc

Very unlikely, but the host can request which feature to start with, skipping any below that feature. Is designed to allow more than 64k of features, so you request the first 64k and then request the next 64k, etc.

harddrv: add to command 0x46

---

bochs/iodev/serial.cc
bochs/iodev/serial.h

The PR adds the name string to the debug output of the serial port. This makes it easier to see what port is getting accessed.

Add names to serial ports

---

bochs/iodev/harddrv.cc
bochs/iodev/hdimage/cdrom.cc

This fixes an error in the Read TOC code and cleans up the return data.
Once it is thoroughly tested, it can be cleaned up more by returning a stream of bytes instead of initializing each byte as it does now.

fix and cleanup Read TOC

---

bochs/iodev/floppy.cc
bochs/iodev/floppy.h

- ~Create a "hack" to counter ReactOS clearing the reset bit and never restoring it to normal operation~
- Modify the source to return in milliseconds and then convert to microseconds for the timer
- Set DOR to normal operation after a reset via the Data Rate Select Register (0x3F4)
- Adjust the timing value to a smaller value (makes the floppy access faster)
- Real hardware sets the LOCK bit on by default
- Real hardware does not set the CHANGE DISK bit at reset
- Modified the BX_DEBUG for the DOR to print decimal instead of hex (value is bool, 0 or 1)
- Fix the `Illegal size for FIFO` error. Zero is a legal size on input, which translate to a size of 1.
- Added Sector numbers to the BX_DEBUG output of the `floppy_xfer` call.
- Fixed the `DUMP_REGISTERS` command to show the EOT value.

Try to make the fdc more like real hardware

---

bochs/bios/rombios.c

Simply adding service Int13h/0x0D
See https://github.com/fysnet/i440fx/issues/10
DOS 7.11 boots with rombios.c without this addition, but you may want to add it anyway.
I don't think there is anything different, as far as emulation is concerned, between service 0x00 and 0x0D.

Add int13/0x0D

---

bochs/gui/win32paramdlg.cc

The win32 dialog box font is tiny on my 1920x1080 Windows laptop. 
I have made the font less tiny by using the default system font instead.
Left fallback for that one person that wants to build it on Windows XP.
Reason for fallback: [NONCLIENTMETRICS#Remarks](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-nonclientmetricsa#remarks)

Use system font on win32 dialog boxes

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

Several changes were made to allow glxgears to run with early GeForce cards and drivers.
Newer cards and drivers seems to be using shader emulation of fixed pipeline.
* Support for quad strips was added;
* Added basic normal vectors and lighting support;
* Fixed wrong image offset when window is moved off screen to the left;
* Fixes #568 (black window in Windows XP with GeForce 3).
Test program: [glxgears.exe.zip](https://github.com/user-attachments/files/21559485/glxgears.exe.zip).

Improve glxgears support for GeForce

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

* Structure with channel state was named as `gf_channel` and passed as parameter to various functions;
* Initialization of channel state was simplified with `memset` function;
Goal of these modifications is improvement of code readability, there should be no functional changes.

Pass GeForce channel as parameter

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

To make colors appear in glxgears with GeForce 6800 (NV40), partial implementation of vertex shaders was done.
Some vertex shader features may work for NV20 as well; NV35 support still needs to be done.
Also reliability of triangle rendering was improved, it may help with #577.
Slight glitch in gears geometry was left without fixing.

Fix missing colors in glxgears with NV40

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

DirectDraw test from DirectX 9 uses 3D triangles and pixel shaders of GeForce 6800 to render 2D rectangles.
This change implements pixel shader features to get correct black and white colors in such test:
With some drivers only one triangle of the pair is rendered, this problem is not related to pixel shaders.
Also emulation of pixel shaders is slow right now. It can be partially fixed by smarter algorithms, but for now it is more important to improve correctness.

Fix colors of DirectDraw test from DxDiag 4.09 with NV40

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

When DirectX-based program is started in Windows XP with 307.83 GeForce driver installed, driver crashes and operating system switches to 16 color mode.
This change partially implements `GET_REPORT` method, which driver relies on.
Also several cases of missing triangles are fixed.

Fix crash with GeForce driver 307.83 in Windows XP

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

This change allows Ubuntu 10.04.4 to display 3D accelerated text with NV35 and NV40 cards.
Also it allows to render [Basic WebGL - Triangle](https://webglworkshop.com/26/01-triangle.html) page with Firefox.

Make text visible in Ubuntu 10.04 with GeForce

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

This change fixes two problems with Blin (#599): in some places text was mirrored, in other places it was missing.

Fix mirrored text in Blin with GeForce

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

This change fixes rendering of "klk's Simple Plasma" shader ([binary](https://github.com/user-attachments/files/22230931/simpleplasma.zip), [source](https://www.shadertoy.com/view/XsVSzW)).
Additionally, fixes are made for display updates in low resolution modes.

Fix Simple Plasma shader with GeForce

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

This change allows to fix texture distortion visible in Half-Life and 3DMark 99.
Also it adds basic texture support for NV20.

Implement perspective-correct interpolation for GeForce

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

Proper implementation of depth comparison allows lightmaps in Half-Life to be visible.
Additionally, this commit fixes lighting in DxDiag 9 Direct3D 8 cube with NV35 and 81.98 driver.
Also it contains implementation for indexed color textures (`I8_A8R8G8B8`).

Implement depth comparison function for GeForce

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

Some 4D triangles can't be directly projected into 2D triangles. It is possible however after the clipping process, which requires creation of additional triangle sometimes.
This change fixes rendering of [BillBoard](https://github.com/user-attachments/files/22600530/BillBoard.zip) program. Also Half-Life in OpenGL mode looks correct now.

Implement near clipping plane for GeForce

---

bochs/iodev/display/geforce.cc
bochs/iodev/display/geforce.h

This change allows Windows 7 Aero to look mostly fine.

Windows Aero fixes for GeForce

---

bochs/iodev/display/geforce.cc

This change fixes texture coordinates mapping for NV40 (issue #625).

Fix missing text in Ubuntu 10 with NV40

---

bochs/iodev/hdimage/cdrom_win32.cc

If an older Guest is using Direct CD-ROM access on Windows and that disc happens to be a DVD, older guests may not recognize the disk since DVD's may use the UDF file system.
However, this may give the user a false indication that Bochs' direct disc access is malfunctioning.
This patch simply gives an indication in the log file.

DVD indication on Win32 direct access
